### ISSUE TITLE
Asking about the license

### ISSUE THREAD

**Issue by Mohammad-Aliraqi** [a1studmuffin/SpaceshipGenerator#26]
Hi a1studmuffin,

Sorry to contact you like this by creating an issue (do not know how to do so otherwise).

I have purchased many tools to help me in my Sci Fi assets to sell. I am very interested in this plugin to create the basis for my spaceships assets. Meaning, I do not want to sell the results of this plugins directly. Rather, I would like to build upon the generated spaceships using my different tools to create polished and customized ones to sell.

Is this OK?

Regards

**Comment by stanrothstegge** [comment]
Since the code is licensed under MIT license. You would be free to modify and sell it as you wish. 

from the licence file:
>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

**Comment by a1studmuffin** [comment]
Hi @Mohammad-Aliraqi, thanks for checking first. The LICENSE file actually has a specific section covering the procedurally generated content made with this software and all its permutations, which defaults to CC BY 3.0. The main reason I added this was to prevent people generating spaceships with the script, then uploading them verbatim to Turbosquid and other 3D asset sites for resale. Yours is a fairly murky case - if you plan on modifying the spaceships *significantly* from their original design for resale, I don't have too much issue with this, but if you're only talking about a few minor cosmetic tweaks to get around the licensing, then I am not comfortable with this. The problem is it's very difficult to draw a line in the sand on what's acceptable and what's not since it's so subjective, so I think to play it safe I have to respectfully decline and insist that all assets generated with the script are CC BY 3.0. Thanks for understanding!
