### ISSUE TITLE
License makes no sense

### ISSUE THREAD

**Issue by Aspie96** [a1studmuffin/SpaceshipGenerator#40]
> If in doubt, please get in touch. As a rule of thumb I'm fine with anyone
> using these spaceships in commercial works, but I am less okay with people
> selling the spaceship models directly for commercial gain. Use common sense.

Creative Commons Attribution By 3.0 does allow selling the model itself

**Comment by a1studmuffin** [comment]
CC 3.0 is pretty clear as you point out. I'm not going to chase anyone
about license usage, I'm just asking politely to please not directly sell
the models generated by this software.

I could have withheld this plugin for myself and sold the models directly
on Turbosquid etc., but I wanted to share it with the community for
educational reasons, and also as a starting point for other commercial
works that use the models or tech creatively. But selling the generated
models as-is is not creative or clever, so I'm asking politely to please
not use this software for that as it goes against the spirit of the
original reasons I created it.

You're free to ignore my request.

**Comment by velniukas** [comment]
> > If in doubt, please get in touch. As a rule of thumb I'm fine with anyone
> > using these spaceships in commercial works, but I am less okay with people
> > selling the spaceship models directly for commercial gain. Use common sense.
> 
> Creative Commons Attribution By 3.0 does allow selling the model itself

The license needs to be clearer which version of CC it is - and allows for commercial use according to Tldrlegal https://tldrlegal.com/license/creative-commons-attribution-(cc)

**Comment by ldo** [comment]
I have [removed](https://github.com/ldo/blender_spaceship_generator/commit/491e5120985de53be1e0a430b8fe417a8bcffc27) the non-Free clause from my version.

**Comment by a1studmuffin** [comment]
The license file says Creative Commons Attribution By 3.0 in it and links to a website with further information. Is that not specific enough? My addenum in the license file about selling content directly isn't enforceable and is just a request - I elaborated on that above. I'm not understanding what needs to be changed.

**Comment by FAUSheppy** [comment]
The license is unclear, for example, what happens if I use part of your code as per MIT License to create spaceships looking completely different from the ones generated by this version? You still want to enforce the CC part? What if I take it to make buildings instead? I could bundle your code to make an end user create the actual meshes themselves if I really wanted. (Spigot style)

I mean it probably just isn't enforceable, but still, you are creating a lot of uncertainty here :/

**Comment by daarong** [comment]
FAUSheppy, honestly I don't think he wants to talk about it anymore. He's already said:

"... I'm not going to chase anyone about license usage ..."
"... I'm asking politely ... you're free to ignore my request ..."
"... My addenum in the license file about selling content directly isn't enforceable and is just a request ..."

**Comment by a1studmuffin** [comment]
Exactly this. If anyone feels uncertain about the licensing terms, you're free to not use/extend the software or get written clarification from me for your particular project.

But as stated earlier, I'm not going to be enforcing anything as this is a throwaway project I made for fun with zero monetary value. We can debate licensing edge cases all day, but it's an exercise in academia. Let's focus our time on making awesome stuff instead.

I appreciate people bringing the inconsistencies to my attention and will take note for future projects to avoid any ambiguity, but I won't be changing anything with the license and people are free to reach out if they're concerned about liability of their own works because of this.

Thanks for the feedback all. Procedural generation is fun!
