### ISSUE TITLE
I found a seed and set of parameters that causes a reproducible crash

### ISSUE THREAD

**Issue by flarn2006** [a1studmuffin/SpaceshipGenerator#8]
Seed: `walnut!`
Min. Hull Segments: 3
Max. Hull Segments: 6
Create Asymmetry: OFF
Min. Asymmetry Segments: 1
Max. Asymmetry Segments: 5
Create Face Detail: ON
Allow Horizontal Symmetry: ON
Allow Vertical Symmetry: OFF
Apply Bevel Modifier: ON
Assign Materials: ON

Now render it or display it in Material mode. Blender will hang.

**Comment by a1studmuffin** [comment]
Thanks for the report. Which Blender version and platform are you using?

**Comment by flarn2006** [comment]
Blender 2.77 (installed from Steam, but I don't think there's a difference) on Windows 10.

**Comment by Deozaan** [comment]
I tried to reproduce and it didn't hang.

But I didn't have a camera or a light in the scene, so I added those back. Blender stopped responding when I added a lamp (sun) to the scene while viewing it in Material mode.

I tried again, creating the `walnut!` spaceship, then changing to Material mode view, then adding the Sun, and there was no hang. I tried adding a camera, still no hang. I tried adjusting a setting on the spaceship and finally got it to hang.

It's finicky and doesn't always hang.

**Comment by a1studmuffin** [comment]
Thanks for the extra info. Since the hang only occurs after the spaceship script has completed (ie. while tweaking other settings within Blender), it sounds more like a Blender bug. This particular spaceship seed must generate a mesh that makes Blender unhappy somehow, though it's clearly allowing it to be created and manipulated in the editor. I'd expect the bmesh API to complain when the spaceship was being created if it was doing something bad. For now my advice would be to try a different seed. ;)
